### ISSUE TITLE
Packages not on the npm registry

### ISSUE THREAD

**Issue by dervos** [marmelab/aor-graphql#19]
Hi, nice work! When I tried integrate these packages I couldn't find them on NPM. Is it possible to publish them or are there reasons for not doing so?

**Comment by djhi** [comment]
ping @fzaninotto

**Comment by djhi** [comment]
Just released in alpha version:
- https://www.npmjs.com/package/aor-graphql-client-graphcool
- https://www.npmjs.com/package/aor-graphql-client
