### ISSUE TITLE
Reference local schema file instead of the introspection query

### ISSUE THREAD

**Issue by dervos** [marmelab/aor-graphql#20]
Would it be possible to create an option to reference a local `schema.graphql` or `schema.json` file to be used for introspection, instead of running a introspection query?

The ability to pass a schema to the `buildApolloClient` which I retrieved beforehand with for example [get-graphql-schema](https://github.com/graphcool/get-graphql-schema), would be very helpful as my schema doesn't change much.

If I'm not mistaken, it could significantly reduce the initial loading time and perhaps there would no longer be a need for `Admin` to wait for `restClient` to be loaded.

**Comment by djhi** [comment]
That could be a nice addition indeed

**Comment by djhi** [comment]
Released: https://github.com/marmelab/aor-graphql/releases/tag/v0.0.1-1. Thanks @dervos
