### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by mwickett** [marmelab/aor-graphql#36]
I'm exploring the AoR ecosystem and am finding myself confused by all the different packages/repos. Specifically I'm wondering about the graphql (I'm using Graphcool) integration.

This isn't meant as a whiny question, so please don't take it that way. I get that you guys are exploring all kinds of directions, and also, you know...working :)

Thanks for making this, and all the contributions you do.

**Comment by djhi** [comment]
Hi, thanks for the kind words :)

This repository will be the official source for aor/gql integrations provided by our team at marmelab. You might have stumbled upon the old [aor-simple-graphql-client](https://github.com/marmelab/aor-simple-graphql-client)  which was our first attempt at it.

The [aor-graphql-client-graphcool](https://github.com/marmelab/aor-graphql/tree/master/packages/aor-graphql-client-graphcool) in this repository should be usable as we have rebuild the admin-on-rest demo with it. Please give us feedbacks about it :)

We still have to make another client, a rewrite of the `aor-simple-graphql-client` but using the foundations provided by the [aor-graphql-client](https://github.com/marmelab/aor-graphql/tree/master/packages/aor-graphql-client) package in this repository.
