### ISSUE TITLE
Graphcool demo data

### ISSUE THREAD

**Issue by matseriksen** [marmelab/aor-graphql#47]
Is there any way to clone the graphcool schema and demo data to use the demo with your own endpoint?

**Comment by djhi** [comment]
Not currently but that's a good idea. We should make it available in the repository for reference

**Comment by matseriksen** [comment]
Yeah that would be great, makes it a lot easier to learn.

**Comment by djhi** [comment]
About the data, it is already available in the demo [bin folder](https://github.com/marmelab/aor-graphql/tree/master/packages/admin-on-rest-graphql-demo/bin). It includes the raw data from the original aor demo and an utility to import it into graphcool.

However, now that graphcool released their framework, we'll probably use it with docker when we'll find the time

**Comment by matseriksen** [comment]
How do I run the utility? when i use "node importData.js" I get

`(function (exports, require, module, __filename, __dirname) { import gql from 'graphql-tag';
                                                              ^^^^^^
SyntaxError: Unexpected token import`
