### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by matseriksen** [marmelab/aor-graphql#53]
Im trying to implement authentication and are having some problems. Im using the AOR auth guide as reference [https://github.com/marmelab/admin-on-rest/blob/master/docs/Authentication.md](url) 

Do I let express middleware handle auth or can I use graphql directly?
Does anyone have a working auth sample? 

Thanks!

**Comment by djhi** [comment]
Both methods are possible, it's a matter of preferences. However, you'll find more examples on *classic* auth with jwt.

**Comment by djhi** [comment]
Check out this article about it: https://dev-blog.apollodata.com/a-guide-to-authentication-in-graphql-e002a4039d1.

We still have a lot of work on this project. Examples for such cases would be nice. Be patient :)

**Comment by matseriksen** [comment]
So I went with JWT and got it "working", using [this server](https://github.com/StephenGrider/AdvancedReduxCode/tree/master/auth/server). But in the guide you linked to it said: 

> Once the user is authenticated, you simply pass the user information into GraphQL as context.

How would I go about doing this in the aor-graphql demo?
