### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by mrcasablr** [marmelab/aor-graphql#54]
I'm really looking forward to this project!  However I see this - "This is very WIP. It currently requires changes on admin-on-rest which have not been published yet."

I was wondering what the plans are for this to be ready to use in production. Also, does upcoming AOR 2.0.0 release the changes published for graphql to work seamlessly?

**Comment by Toosick** [comment]
We use this project in production just fine. I don't know exactly what they are referring to.

**Comment by djhi** [comment]
This disclaimer is not relevant anymore. I'll remove it ASAP

**Comment by Toosick** [comment]
@djhi Our project has been working off a fork so it doesn't matter but when do you plan to automate lerna publishes using Travis CI? Our fork of this project auto-publishes to npm and commits the version bump on Github with Travis CI.
