### ISSUE TITLE
ReferenceManyField

### ISSUE THREAD

**Issue by humbertocruz** [marmelab/aor-graphql#55]
Hello, how should I use this ReferenceManyField ? I tried something like:
`<ReferenceManyField label="Grupos" reference="Group" target="users">`
but  I got:
`GraphQL error: Variable '$filter' expected value of type 'GroupFilter' but got: {"users":{"id":"cja7m71tyoen201503owjey8g"}}. Reason: 'users' Field 'users' is not defined in the input type 'GroupFilter'`

thanks

**Comment by humbertocruz** [comment]
Hello, well I found that the problem it's with the relation field. When I create a relation between types on graphcool it names then by the related type without the _id sufix. That would be changed in the schema. But the value of this relational fields are a object with a id and the type related.

**Comment by philipheinser** [comment]
@humbertocruz What is your solution to that? I have the same problem. If target was allowed to be a function we could return a array of ids for that field.

**Comment by vysakh0** [comment]
@humbertocruz @philipheinser Can you please share if you had fixed this?

```js
export const UserShow = (props) => (
    <Show {...props}>
        <SimpleShowLayout>
            <TextField source="name" />
            <TextField source="phone" />
            <ReferenceManyField label="Replies" addLabel={false}  reference="Reply" target="user.id">
                <Datagrid filter={{ text: 'approved' }}>
                    <TextField source="text" />
                </Datagrid>
            </ReferenceManyField>
        </SimpleShowLayout>
    </Show>
);
```
<img width="537" alt="screen shot 2018-03-06 at 6 02 18 pm" src="https://user-images.githubusercontent.com/1475197/37032450-959c9902-2168-11e8-93b2-22bdbfcc1a00.png">
<img width="567" alt="screen shot 2018-03-06 at 6 02 27 pm" src="https://user-images.githubusercontent.com/1475197/37032451-95ca7e3a-2168-11e8-9799-b51f7154d8e2.png">
I'm getting this error!

**Comment by humbertocruz** [comment]
sorry, I didn't find a solution and change my App to use PouchDB.

**Comment by vysakh0** [comment]
@humbertocruz oh okay, thank you 👍 I have found a solution.

For those who have the problem.

1. 

```js
export const UserShow = (props) => (
    <Show {...props}>
        <SimpleShowLayout>
            <TextField source="name" />
            <TextField source="phone" />
            <ReferenceManyField label="Replies" addLabel={false}  reference="Reply" target="user">
                <Datagrid>
                    <TextField source="text" />
                </Datagrid>
            </ReferenceManyField>
        </SimpleShowLayout>
    </Show>
);
```

2. Make sure you define the Resource that you're trying to access under `<Admin>` component whether you're going to use it or not. In my case `Reply` is not required to appear in menu, but if I want it to use it as a`Reference` field, I have to define it as a Resource
