### ISSUE TITLE
Which is the recommended client for a standard GraphQL setup?

### ISSUE THREAD

**Issue by jamesjwarren** [marmelab/aor-graphql#56]
Which client is best suited to a standard GraphQL setup using only GraphQL-JS on the backend?  I would assume `aor-graphql-client`, as `aor-graphql-client-simple` seems to no longer exist. However the docs say this should not be used directly... in cases where graphcool is not being used are we required to create our own client with `aor-graphql-client`?

>This is a very low level library which is not meant to be used directly unless you really want full control or are building a custom GraphQL client.
>
>It provides the foundations for other packages such as:
>
>aor-graphql-client-simple
>aor-graphql-client-graphcool

**Comment by djhi** [comment]
That will be `aor-graphql-client-simple` once we will have time to make it. However, `aor-graphql-client` indeed provides the foundations for a custom one. It is the glue between an Apollo client and aor.

For now, you'll have to make your own and read the code of the `aor-graphql-client-graphcool` client as inspiration.
