### ISSUE TITLE
WIP... which branches for Apollo-2...?

### ISSUE THREAD

**Issue by hubert-associates** [marmelab/aor-graphql#59]
Hi, thanks for this great combination (admin-page on reactjs, material-ui, apollo, graphql). Now, I'm looking to access the latest Apollo-2 cut so I don't re-invent. Precisely which branches should I fetch?

**Comment by matseriksen** [comment]
The "aor-graphql-client" got updated to Apollo 2 on the main branch.

**Comment by hubert-associates** [comment]
I thought still WIP since -- the package.json still uses apollo-client 1.9.3 there? https://github.com/marmelab/aor-graphql/blob/master/packages/aor-graphql-client/package.json 
Am I in the wrong branch?

**Comment by djhi** [comment]
Well, it has not been updated to use Apollo 2. See https://github.com/marmelab/aor-graphql/pull/57. It has been updated to **accept your own client** which can be from Apollo 2. However, this has not been released on npm yet. You can fetch it from the `master` branch though.

We are in the process of migrating all `admin-on-rest` projects in the root [repository](https://github.com/marmelab/admin-on-rest/tree/next), including those. Work is happening in the `next` branch. When it will be done, we will migrate our graphql packages to use Apollo 2.

**Comment by hubert-associates** [comment]
Dumb question, I am finding different sources of the same demo under:
https://github.com/marmelab/admin-on-rest-graphql-demo/blob/master/src/aorApolloClient.js
and
https://github.com/marmelab/aor-graphql/blob/master/packages/admin-on-rest-graphql-demo/src/aorApolloClient.js

Is there a clean way to clone the newer (lerna?) packages one?
