### ISSUE TITLE
Custom client overwritten

### ISSUE THREAD

**Issue by jamesjwarren** [marmelab/aor-graphql#60]
I'm using the latest master branch, trying to pass a custom apollo client as per [the docs](https://github.com/marmelab/aor-graphql/tree/master/packages/aor-graphql-client#customize-the-apollo-client).
```js
buildApolloClient({ client: new ApolloClient(...) });
```

However the client seems to be getting overwritten. Taking a closer look it seems to be happening at this line: https://github.com/marmelab/aor-graphql/blob/master/packages/aor-graphql-client/src/index.js#L46

Should this be using an OR operator instead? Otherwise it always continues to build a new client. Or am I missing something?
```js
const client = clientObject || buildApolloClient(clientOptions);
```

**Comment by djhi** [comment]
Right, I merged this one too fast... Can you make a PR ?

**Comment by jamesjwarren** [comment]
Sure 👍
